### ISSUE TITLE
Crash when used with Google Maps

### ISSUE THREAD

**Issue by adithyaxx** [kmcgill88/admob_flutter#100]
Great work on this package! This is the only package that offers a truly fluttery way to incorporate ads as a widget. 

I have tried it out and it works fine on android and on the iOS simulator. However, when run on a physical iOS device, my app crashes. I did some testing and found out that the crash only occurs when the Google Map widget is present in the same Scaffold as the banner. I have tried placing the banner in both a stack and a column yielding the same results. This seems like a very strange behaviour and I am not able to get an debug info on the crash either.

**Comment by EliasDeuss** [comment]
@adithyaxx Can you do flutter doctor -v and give me the output.

**Comment by adithyaxx** [comment]
Also, I just switched to the master channel (1.10.15-pre.368) and the crash is not happening anymore. Previously, I was on the dev channel when I was experiencing this issue. So I am not sure whether it's a problem with this package or flutter itself.

And yes I tested it on both platforms on both simulators and physical devices. The crash was consistently occurring only on physical iOS devices on both iOS 12.4 and iOS 13.1.3.

**Comment by adithyaxx** [comment]
To add on, even in 1.10.15-pre.351 the crash is still present. So maybe that narrows down and helps with identifying what changed in flutter with the last few commits.

**Comment by EliasDeuss** [comment]
@adithyaxx It could be a issue with flutter itself and the fix is currently only in the master channel.

**Comment by adithyaxx** [comment]
Since the stable channel is now 1.12.13, the issue seems to be fixed.
