### ISSUE TITLE
Ads Not Showing When Using Visibility Widget and Changing States on On load event 

### ISSUE THREAD

**Issue by kibhub** [kmcgill88/admob_flutter#103]
`Visibility(
            visible: bannerAdVisibility,
            maintainState: true,
            child: Container(
              height: 50,
              width: 320,
              margin: EdgeInsets.only(bottom: 5.0),
              child: AdmobBanner(
                adUnitId: "",
                adSize: bannerAd,
                listener: (AdmobAdEvent event, Map<String, dynamic> args) {
                  if (event == AdmobAdEvent.loaded) {
                    setState(() {
                      bannerAdVisibility = true;
                    });
                  }
                },
              ),
            ),
          ),`

**Comment by EliasDeuss** [comment]
@kibhub I don't think you can do what you want to do with a Visibility widget because the banner ad widget has to be always visible. Am I correct @kmcgill88 ?

**Comment by henry2man** [comment]
> @kibhub I don't think you can do what you want to do with a Visibility widget because the banner ad widget has to be always visible. Am I correct @kmcgill88 ?

I agree, @kibhub you have to reserve some space for banners. Using these techniques can confuse users, is against AdMob rules, and may lead to your account being suspended.
