### ISSUE TITLE
unfortunately, kaka_tags has stopped Working

### ISSUE THREAD

**Issue by yadsbah** [kmcgill88/admob_flutter#108]
after I added   admob_flutter: ^0.3.4 to my app dependencies. 

the app stopped working and when I try to build it. it says unfortunately, kaka_tags has stopped Working

No error shows in Debug Console.

![Screenshot (11)](https://user-images.githubusercontent.com/47110831/69498396-b89a0000-0ef8-11ea-92a0-7de64a858b08.png)

**Comment by night-wielder** [comment]
Checking in. I have the same issue!

**Comment by night-wielder** [comment]
Shit! I was so stupid. Just add your app ID in the manifest and this will be fixed!

**Comment by EliasDeuss** [comment]
@yadsbah have you tried what @night-wielder has suggested?

**Comment by samgermain** [comment]
@night-wielder Could you elaborate please, I don't know where manifest is or what the app id is
