### ISSUE TITLE
Can't run flutter app when admob_flutter is added as a dependency due to error "Waiting for observatory port to be available..."

### ISSUE THREAD

**Issue by 99darshan** [kmcgill88/admob_flutter#112]
I created a new flutter project **( Flutter 1.12.13+hotfix.5 )** then added  admob_flutter as a dependency in package.yaml. When I try to run the app it crashes.

`flutter run --verbose` gives an message **"Waiting for observatory port to be available..."** and it gets stuck there 

I tried removing admob_flutter as a dependency and added other packages like url_launcher, flutter_pdfview, etc. and the app works just fine. 

Not sure if there is a problem with my dev env setup or problem with the package itself. I created a new project and added admob_flutter to the dependency, that's all I did. 

P.S. I am facing similar issue with firebase_admob as well.

**Comment by comlaterra** [comment]
I've solved by adding the information in the AndroidManifest as said here: https://github.com/kmcgill88/admob_flutter/wiki/Installation#android

Cheers

**Comment by comlaterra** [comment]
So, I've solved it by running first:
```
flutter clean
```
Adding 
```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>
```
to the AndroidManifest.xml and then running it either from console or from VSCode.
> Note: After building from console with `flutter run` and before building with VSCode I need to do `flutter clean` again.

Hope this helps

**Comment by 99darshan** [comment]
@comlaterra Thank you for your help, I tried the steps you've mentioned; unfortunately, the issue is not resolved... I am still getting the error:  [   **+1 ms] Waiting for observatory port to be available...**

**Comment by EliasDeuss** [comment]
If it’s happening to you with the firebase_admob package too it might be a flutter issue but I will mark this issue as a bug for now.

**Comment by anderspetersson** [comment]
Had this error and spent few hours scraching my head, not sure what part was the magic bullet, but I solved this by setting:

android/build.gradle:

```
dependencies {
    classpath 'com.android.tools.build:gradle:3.5.0'
    classpath 'com.google.gms:google-services:4.3.3'
}
```

android/app/build.gradle:
```
dependencies {
    ...
    implementation 'com.google.android.gms:play-services-ads:16.5.0'
}
```

changing  `distributionUrl` in android/gradle/wrapper/gradle-wrapper.properties to `https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

android/app/source/main/AndroidManifest.xml
Making sure
```
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-XXXXXXXXXXXX~XXXXXX"/>
```
was set as a direct child to `<application>` and not under `<activity>`

Flutter 1.12.13+hotfix5
admob_flutter: ^0.3.1

**Comment by 99darshan** [comment]
Thanks @anderspetersson, I finally resolved the issue. Here is what I did, I made changes to the android/build.gradle and android/app/build.gradle as you've suggested. 

Also, I was mistakenly using AD Unit ID instead of Admob Application Id in the android manifest, which have been causing the error. 

The issues is now resolved. Thanks. :)

**Comment by EliasDeuss** [comment]
ok @99darshan Going to be closing this now. Thank you @anderspetersson for helping.
