### ISSUE TITLE
Ads Not Showing after I signed the app

### ISSUE THREAD

**Issue by heshaShawky** [kmcgill88/admob_flutter#121]
The Ads was working fine with real ads ids not testing once, but after I have updated the `build.gradle` file to signing my app 

Then I hit `flutter run -d <MyAppID> --release` the ads not working and returns `error code 3 `on `console` but working fine in debug mode `flutter run -d <MyAppID>` without `--release`

Working also fine if I get my `build.graddle` like it before (default).

**Comment by EliasDeuss** [comment]
@heshaShawky did you add this to your manifest?

```
<manifest>
  <application>
    <meta-data
      android:name="com.google.android.gms.ads.APPLICATION_ID"
      android:value="Your ca-app-pub here"/>
  </application>
</manifest>
```

**Comment by heshaShawky** [comment]
Yea I did of course, The issue from google not flutter the adds need time to recognize the new app ids so after published the app the ads just get works  

> @heshaShawky did you add this to your manifest?
> 
> ```
> <manifest>
>   <application>
>     <meta-data
>       android:name="com.google.android.gms.ads.APPLICATION_ID"
>       android:value="Your ca-app-pub here"/>
>   </application>
> </manifest>
> ```
