### ISSUE TITLE
Needs Swift-based flutter project. Default Objective C won't build

### ISSUE THREAD

**Issue by daneed** [kmcgill88/admob_flutter#123]
Hi!
I generated my flutter project with default settings. This generates objective-c source and xcode project files for ios. If I try to use admob_flutter in my project, the result is compile error, which is related to Swift, and unresolved symbols (this is a linking error).
If I regenerate my project's ios part with the -i swift flag: admob_flutter works well.

Is It a known issue? It is easily reproducable.
daneed

**Comment by kmcgill88** [comment]
This is a known issue. If you could PR a fix so this is compatible with Obj-C & Swift based projects that would be great. I don't use Obj-C anymore so I don't really have the energy to support it.

**Comment by daneed** [comment]
Hi!
OK, thank you. I just wrote this, because Flutter's default behavior is (as i know), that it creates obj-C project, instead of Swift!
So, maybe this would be good to emphasize, that with such kind of project, this admob_flutter won't work. Like, it would be clever to be put into README. This would spare time for users like me.
Thanks for the answer!
Best regards, Daniel

**Comment by ZhangPingFan** [comment]
https://stackoverflow.com/questions/52244346/how-to-enable-swift-support-for-existing-project-in-flutter

**Comment by kmcgill88** [comment]
> https://stackoverflow.com/questions/52244346/how-to-enable-swift-support-for-existing-project-in-flutter

@ZhangPingFan could you please PR this link to the README under FAQ please

**Comment by kmcgill88** [comment]
Thanks @ZhangPingFan !
