### ISSUE TITLE
Smart Banner is crashing the UI

### ISSUE THREAD

**Issue by rajeshjeshar** [kmcgill88/admob_flutter#124]
While choosing banner ad=>Smart banner,it crashes the UI.
In case [Adaptive Banners](https://developers.google.com/admob/android/banner/adaptive) is possible to implement that will be helpful

**Comment by EliasDeuss** [comment]
@rajeshjeshar Adaptive Banners has been added?

**Comment by rajeshjeshar** [comment]
@EliasDeuss I'm sorry i don't have idea about that,to be honest i've stopped implementing google ads
