### ISSUE TITLE
User metrics always shows 0

### ISSUE THREAD

**Issue by tonypottera24** [kmcgill88/admob_flutter#128]
Does anyone know why my "User metrics" always shows 0?
I'm using `admob_flutter: ^0.3.4`
Apps > App overview > User metrics
<img width="482" alt="Screen Shot 2020-02-06 at 6 42 16 PM" src="https://user-images.githubusercontent.com/3013707/73929822-7a658780-4910-11ea-919b-8764a4e8875f.png">

**Comment by jonatadashi** [comment]
Here also! Using 1.0.0-beta

**Comment by atereshkov** [comment]
Tap the "Learn more" url. It should be enabled like stated here https://support.google.com/admob/answer/9263723?hl=en

But in my case it looks like I've enabled it (or it was enabled by default) but I also have zeroes.

**Comment by tonypottera24** [comment]
I moved to `firebase_flutter` and everything works as expected.
