### ISSUE TITLE
This plug-in can not be installed.

### ISSUE THREAD

**Issue by kyungjoongo** [kmcgill88/admob_flutter#13]
This plug-in can not be installed.
Do not you develop this anymore?

**Comment by Bgumel** [comment]
the same issue when I import the package
`Target of URI doesn't exist: 'package:admob_flutter/admob_flutter.dart'`
and the package exists in 
`C:\Users\{PC Name}\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org`

**Comment by kmcgill88** [comment]
What's the status of this issue @kyungjoongo @Bgumel?

**Comment by EliasDeuss** [comment]
@kyungjoongo @Bgumel I am closing this issue because it's inactive. If you are still having the issue please reopen the issue with more info.
