### ISSUE TITLE
Migrate to the Play Install Referrer API 

### ISSUE THREAD

**Issue by gladiator2b** [kmcgill88/admob_flutter#132]
hi,
I received this email from Google, I don't know what to do because it comes from admob_flutter

 Hello Google Play Developer,

We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.

Action required

Migrate to the Play Install Referrer API to track your app installs for the following apps and/or games.

problem :
com.google.android.finsky.BIND_GET_INSTALL_REFERRER_SERVICE)

**Comment by EliasDeuss** [comment]
Can you look at this @kmcgill88

**Comment by gladiator2b** [comment]
hi,
i think the problem will be for all admob_flutter users

**Comment by YoussefKababe** [comment]
Hello @gladiator2b,

We are not using install_referrer in this package directly, it’s something that one of the packages we depend on uses (com.google.firebase:firebase-ads:18.3.0). You really have nothing to do by yourself for now, and we can’t do anything either. We just have to wait for google to release an updated firebase-ads package that doesn't use the install_referrer intent.

Check this out: https://stackoverflow.com/questions/59274930/install-referrer-intent-deprecation
