### ISSUE TITLE
How to use handleEvent method?

### ISSUE THREAD

**Issue by Purus** [kmcgill88/admob_flutter#15]
How do I define Listener for a Reward Video while showing it? The docs shows to add listeners when creating the initial AdmobReward object.

But I want to use it later in the life cycle of the page.

I see there is a method called `handleEvent`.. but how do I pass values to it? Can you please share some example on using this method.

**Comment by EliasDeuss** [comment]
@Purus There is an example on how to do this in [admob_flutter/example/lib/main.dart](https://github.com/kmcgill88/admob_flutter/blob/master/example/lib/main.dart) Please reopen if this doesn't answer your question.
