### ISSUE TITLE
Ads only work in debug mode. When sign and create release app. Ads stop showing.

### ISSUE THREAD

**Issue by miwaigyi** [kmcgill88/admob_flutter#151]

**Comment by EliasDeuss** [comment]
@miwaigyi Can you provide more info?

**Comment by amanv8060** [comment]
same happening with me

**Comment by amanv8060** [comment]
what info do you need?

**Comment by saulowilson** [comment]
Provide more info of your approach that you are using to implement ads. Is your ads provider Admob? How are your AndroidManifest?

**Comment by pallavbohara** [comment]
Yes. Same problem.Not able to see bannar in release mode . I am using version admob_flutter: **"^0.3.4"** and with following version for flutter doctor

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.0)
> [√] VS Code (version 1.44.2)
> [!] Connected device
>     ! No devices available

Also RewardAd, InterstialAd ads are not working in debug mode.

**Comment by miwaigyi** [comment]
Everything working fine after upload application to playstore. Tips- Don't sign app if u don't intent to upload ur app to playstore.
