### ISSUE TITLE
Fail on Pod dependency

### ISSUE THREAD

**Issue by pazhut** [kmcgill88/admob_flutter#152]
i got the following error for the POD installer:

    [!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
      In snapshot (Podfile.lock):
        FirebaseAnalytics (= 6.4.0)

      In Podfile:
        admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 0.3.4, which depends on
          FirebaseAnalytics (~> 6.1.3)

only that 6.4.0 seems newer version than 6.1.3, any advice?

**Comment by pazhut** [comment]
Found an issue with the Podfile.lock, resolved

**Comment by eakdogan** [comment]
Can you tell me how you resolved this?

**Comment by pazhut** [comment]
i had to remove the pod.lock file which caused new versions to get installed
