### ISSUE TITLE
How to add test device?

### ISSUE THREAD

**Issue by ouzari** [kmcgill88/admob_flutter#155]
I did a lot of search and I did not find how to add a test device with this plugin like :
RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("21FD3848F44F7D9486A53034D154566F")
Please help. 
And thank you for the plugin.

**Comment by EliasDeuss** [comment]
Currently not a way in this plugin @ouzari . There is a open pull request for it though #90
