### ISSUE TITLE
ads not work in release mode

### ISSUE THREAD

**Issue by amanv8060** [kmcgill88/admob_flutter#157]
Ads work only when 
the signing config is set to debug

**Comment by yiss** [comment]
This happens to me as well, it just need some time to get approved. For me once the app was live on the app store it was working fine

**Comment by amanv8060** [comment]
Seems a Proguard issue . Solved after that

**Comment by onstonboy** [comment]
@amanv8060 , Hi, I got same issue. how do you fix it?

**Comment by amanv8060** [comment]
https://stackoverflow.com/a/61539203/13189522
