### ISSUE TITLE
Ad failed to load : 3

### ISSUE THREAD

**Issue by hsnbsst** [kmcgill88/admob_flutter#159]
Ads are not showing on my phone, but the emulator also shows in test mode. as the error code: Ad failed to load: 3 
i'm also sure you did everything right

**Comment by therichiekumar** [comment]
I face the same issue

**Comment by hsnbsst** [comment]
admob income is very low due to this event, and admob match is 28%

**Comment by yiss** [comment]
Do you have any special proguard rules ? are you testing on device or emulator ?

**Comment by hsnbsst** [comment]
we have no special protection rules. receive impressions on test device but not on actual device

**Comment by y4gamilight** [comment]
because in this version still can't add targetinfo.
In target info you will add device id to test 

I found a folk branch https://github.com/jpainam/admob_flutter will resolve your problem . He created merge request but it is failure

**Comment by danielgchap** [comment]
I face the same issue:

I/Ads     (23019): Use AdRequest.Builder.addTestDevice("xxxx") to get test ads on this device.
I/Ads     (23019): Ad failed to load : 3
I/Ads     (23019): Use AdRequest.Builder.addTestDevice("xxxx") to get test ads on this device.
W/Ads     (23019): Not retrying to fetch app settings
I/Ads     (23019): Ad failed to load : 3

**Comment by Nikolak47** [comment]
@y4gamilight did you manage to make it work with the code from his branch ?
Because I still can't.
I set my device ID to 'testDevices', I did everything right, but still the ads are not showing.
Has anyone found a fix for this ?
PS: My app is not published in playstore, but I don't think that will be a problem.

**Comment by y4gamilight** [comment]
@Nikolak47  you use can implement plugin with syntax
dependencies:
  plugin1:
    git:
      url: git://github.com/flutter/plugin1.git

**Comment by Nikolak47** [comment]
@y4gamilight I did it.
Still doesn't work.
I implemented this branch, but still can't see the ads on my phone, event though I put my deviceID in test devices

**Comment by kmcgill88** [comment]
see https://github.com/kmcgill88/admob_flutter/issues/161
