### ISSUE TITLE
Ads shows  on debug mode but not on client devices

### ISSUE THREAD

**Issue by ron109** [kmcgill88/admob_flutter#16]
Hey, I have used this library in order to present banner ads.
In the debug mode it shows me local ads..
I published my app, but when users download it all it show is white blank banner..
my app id and banner id are correct because on debug it does show me local real ad but under test ad (i have replaced the ids and made sure they are all right)
any solution?

**Comment by rostopira** [comment]
I had similar issue, found out, that you are required to set that app contains adds in Google Play Console

**Comment by kmcgill88** [comment]
@ron109 what's the status of this? Get this worked out?

**Comment by nbfajanilan** [comment]
Encountering the same issue. Worked perfectly during testing but doesn't show ads after publishing the app. Is there any status update?

**Comment by kmcgill88** [comment]
@nbfajanilan have you completely setup your admob account? Liked a bank account? Filled out all the tax forms? I believe this can cause test ads to work but real ads will not show up in production unless these are completed.

**Comment by nbfajanilan** [comment]
@kmcgill88 yes, I already completed setting up my admob account. I have other app which uses firebase_admob and it is working properly. It proves my account is not a factor here. During testing, I used my admob appId and bannerId.

For my new app, admob_flutter is more suitable to the layout I need hence I preferred using it.

**Comment by nbfajanilan** [comment]
Just an update. The ads now appears in some instances after few days. 

Not consistently in fact very rarely but I guess it is now up to admob's algorithm when the ads will be loaded.

**Comment by rahulshukla-rs** [comment]
I got the solution,
Steps are as follows:
1. Add plugin to pubspec.yaml
 `firebase_admob: ^0.9.0+3`
2. In main() function
Remove: `Admob.initialize('YOUR_ADMOB_ID');`
Add: `FirebaseAdMob.instance.initialize(appId: YOUR_ADMOB_ID);`

Other things remain unchanged, It will work.
:)

**Comment by EliasDeuss** [comment]
> I got the solution,
> Steps are as follows:
> 
> 1. Add plugin to pubspec.yaml
>    `firebase_admob: ^0.9.0+3`
> 2. In main() function
>    Remove: `Admob.initialize('YOUR_ADMOB_ID');`
>    Add: `FirebaseAdMob.instance.initialize(appId: YOUR_ADMOB_ID);`
> 
> Other things remain unchanged, It will work.
> :)

@ron109 @nbfajanilan Where you able to fix it with this solution? Thank you @rahulshukla-rs for the quick fix.

**Comment by kmcgill88** [comment]
stale, closing.
