### ISSUE TITLE
Ads are not loading

### ISSUE THREAD

**Issue by Nikolak47** [kmcgill88/admob_flutter#161]
I integrated everything as in the tutorial, but the ads are not displaying/loading.
PS: When I use firebase_admob plugin, the ads are loading.

**Comment by LeonIPierre** [comment]
do you see any errors when brining up logcat?

**Comment by Nikolak47** [comment]
Actually, yes.
Usually 'Error: 3', when I try to open interstitial ad.

**Comment by danielgchap** [comment]
I believe I'm having a similar issue:

W/Ads     (23019): Not retrying to fetch app settings
I/Ads     (23019): Ad failed to load : 3
I/Ads     (23019): Ad failed to load : 3

Thanks!

**Comment by LeonIPierre** [comment]
A quick search yields this result:
https://stackoverflow.com/questions/33566485/failed-to-load-ad-3

Do ads using test ids load?

**Comment by danielgchap** [comment]
> A quick search yields this result:
> https://stackoverflow.com/questions/33566485/failed-to-load-ad-3
> 
> Do your banner ads load correctly?
> Do ads using test ids load?

Test ads, of any kind, work fine. Banner ads load, but only with test ids. Otherwise, they are just a black box. iOS continues to work just fine. Thanks.

**Comment by kmcgill88** [comment]
## Ensure you are using the correct `App Id + Ad Id` combinations per platform.

[example code](https://github.com/kmcgill88/admob_flutter/blob/master/example/lib/main.dart#L252)

You can use these test App ID's from Admob for development:
```
Android: ca-app-pub-3940256099942544~3347511713
iOS: ca-app-pub-3940256099942544~1458002511
```

## Android Specific Setup
```xml
<manifest>
  <application>
    <meta-data
      android:name="com.google.android.gms.ads.APPLICATION_ID"
      android:value="ca-app-pub-3940256099942544~3347511713"/>
  </application>
</manifest>
```

## iOS Specific Setup
Update your `Info.plist` per [Firebase instructions](https://developers.google.com/admob/ios/quick-start#update_your_infoplist).
```xml
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544~1458002511</string>
```




## During runtime get the correct ad id per platform.
```dart
String getBannerAdUnitId() {
  if (Platform.isIOS) {
    return 'ca-app-pub-3940256099942544/2934735716';
  } else if (Platform.isAndroid) {
    return 'ca-app-pub-3940256099942544/6300978111';
  }
  return null;
}

String getInterstitialAdUnitId() {
  if (Platform.isIOS) {
    return 'ca-app-pub-3940256099942544/4411468910';
  } else if (Platform.isAndroid) {
    return 'ca-app-pub-3940256099942544/1033173712';
  }
  return null;
}

String getRewardBasedVideoAdUnitId() {
  if (Platform.isIOS) {
    return 'ca-app-pub-3940256099942544/1712485313';
  } else if (Platform.isAndroid) {
    return 'ca-app-pub-3940256099942544/5224354917';
  }
  return null;
}
```

**Comment by danielgchap** [comment]
Hi there, 
yes I have performed all of this correctly. Should I be seeing them in my debug builds or do I need to release an apk signed build through the Google close/internal testing track in order to see them?

Thanks

**Comment by danielgchap** [comment]
This was the resolution. Put an apk into the internal test track on your Google Play account (make sure it's published. Roll it out. Wait a few hours. Download that APK to your test device with your test account that you declared in the internal test testers section. Bam. Ads show up)

Thank you so much for making this pub and for continuing to support it!
God bless

**Comment by erperejildo** [comment]
> This was the resolution. Put an apk into the internal test track on your Google Play account (make sure it's published. Roll it out. Wait a few hours. Download that APK to your test device with your test account that you declared in the internal test testers section. Bam. Ads show up)
> 
> Thank you so much for making this pub and for continuing to support it!
> God bless

I can display the ads ok in Android but not in iOS. Is that because I don't have the iOS version released yet?
