### ISSUE TITLE
Interstitial failedToLoad won’t fire 

### ISSUE THREAD

**Issue by DeadlyMissile** [kmcgill88/admob_flutter#163]
Interstitial failedToLoad won’t fire. All other listeners are working fine

**Comment by DeadlyMissile** [comment]
@kmcgill88 
AdmobInterstitial _createInterstitial() {
 return AdmobInterstitial(
    listener: (AdmobAdEvent event, Map<String, dynamic> {
 if (event == AdmobAdEvent.failedToLoad) {
   print(“Ad failed to load”);
});
}
This never prints. The other events like loaded and closed work fine and print

**Comment by kmcgill88** [comment]
I guess I don't understand. Is this a problem? `AdmobAdEvent.failedToLoad` only fires when there is a failure to load the ad.

**Comment by kmcgill88** [comment]
No response. Closing.
