### ISSUE TITLE
Add the changes to Android Manifest in Readme

### ISSUE THREAD

**Issue by SenAlexandru** [kmcgill88/admob_flutter#165]
Hi,
I believe it is important to specify in the readme file (here and in pub.dev) that the below changes need to be made in the AndroidManifest

<meta-data
    android:name="com.google.android.gms.ads.APPLICATION_ID"
    android:value="[ADMOB_APP_ID]"/>

Otherwise, the package works ok for me and thank you a lot for all your work!

**Comment by kmcgill88** [comment]
I'll get this back into the readme in the next PR! Thank you!
