### ISSUE TITLE
How to show a pre loading widget till the ad been loaded 

### ISSUE THREAD

**Issue by heshaShawky** [kmcgill88/admob_flutter#168]
The ad because it's not loaded when my app starting shows a black box on the widget tree, is there an option to put some indicator or a widget as a preloading for a better look.

**Comment by kmcgill88** [comment]
Built into `admob_flutter`, no, sorry there isn't. You would have to implement that yourself.

```
Container(
  color: Colors.red, // Set your own color here.
       child: AdmobBanner(
                      adUnitId: getBannerAdUnitId(),
                      adSize: bannerSize,
                      listener:
                          (AdmobAdEvent event, Map<String, dynamic> args) {
                        handleEvent(event, args, 'Banner'); // listen for banner events here
                      },
                    ),
                  ),
```

See the example app for more details. https://github.com/kmcgill88/admob_flutter/blob/support-device-test-ids/example/lib/main.dart#L226
