### ISSUE TITLE
The test ads not showing in real device using debugApk

### ISSUE THREAD

**Issue by johng2t** [kmcgill88/admob_flutter#175]
I am new to flutter, I used admob_flutter to display the ads in my application. It is working when I run `flutter run` in emulator, I am seeing the test ads. But when I do the same in real device the test ads are not showing. Guide me how to display the test ads in real device.

**Comment by Tirth7545** [comment]
Please Share Your Code

**Comment by norbertkross** [comment]
facing this same issue. Anyone know how this can be fixed
