### ISSUE TITLE
Error in building flutter app

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [kmcgill88/admob_flutter#179]
I'm getting the following error while building flutter app. Can somebody help me in resolving this issue ??
A problem occurred configuring project ':admob_flutter'.
> Could not resolve all artifacts for configuration ':admob_flutter:classpath'.
   > Could not resolve org.checkerframework:checker-qual:2.5.2.
     Required by:
         project :admob_flutter > com.android.tools.build:gradle:3.3.0 > com.android.tools.analytics-library:shared:26.3.0 > com.google.guava:guava:26.0-jre

**Comment by amanv8060** [comment]
can you draw some more insights ?

**Comment by kpradeepkumarreddy** [comment]
This issue is resolved. [https://stackoverflow.com/questions/62360882/gradle-build-error-fatal-error-checker-qual-2-5-2-pom21-content-is-not-allo](url)

**Comment by kpradeepkumarreddy** [comment]
This issue is resolved. [https://stackoverflow.com/questions/62360882/gradle-build-error-fatal-error-checker-qual-2-5-2-pom21-content-is-not-allo](url).  Clearing the cache fixed the issue.
