### ISSUE TITLE
Rewarded ads cannot load second time

### ISSUE THREAD

**Issue by cihadturhan** [kmcgill88/admob_flutter#183]
I'm trying loading another rewarded ad after first one is completed. But when I call `reward.load()` function, I see the following error:

`flutter: ADMOB AdmobAdEvent.failedToLoad, {errorCode: Request Error: Will not send request because ad has been used.}`

I checked why this happens. It looks like we need to destroy rewarded ad instance and recreate for  the next ad. See [here](https://stackoverflow.com/a/30784164/856702)

It's not how it is in your example code. What is the practice for multiple rewarded/interstitial ads?

**Comment by cihadturhan** [comment]
Yes, creating new instance worked.
```diff
    rewardAd = AdmobReward(
      adUnitId: getRewardBasedVideoAdUnitId(),
      listener: (AdmobAdEvent event, Map<String, dynamic> args) {
        if (event == AdmobAdEvent.closed){
+           if(GetPlatform.isIOS){
+              rewardAd.dispose();
+              rewardAd = AdmobReward(adUnitId: rewardedAdUnitId, listener: handleEvent);
+          }
          rewardAd.load();
        }
        handleEvent(event, args, 'Reward');
      },
    );
```
I think this needs to be fixed on swift code, but if someone needs a workaround, use the the code above.

**Comment by kmcgill88** [comment]
@cihadturhan thanks for investigating this. [The docs](https://developers.google.com/admob/ios/rewarded-ads#using_gadrewardedaddelegate_to_preload_the_next_rewarded_ad) state `GADRewardedAd is a one-time-use object`. I recently updated this api and it looks like the sdk changed from a reuse model to a one-time-use.

Need to double check the android side too.

If you have bandwidth, a PR would be appreciated 😄. Not sure when my schedule will allow me to get to this.

**Comment by cihadturhan** [comment]
It’s working fine without destroying the object. I even tested and released my app with a workaround above. 
Unfortunately I don’t have too, but I’ll try after a week or so. 
Thanks for the library. It’s amazing you provided a better alternative than google’s :)

**Comment by kmcgill88** [comment]
@cihadturhan I fixed this for iOS!

https://github.com/kmcgill88/admob_flutter/pull/185 will merge and publish beta update.

**Comment by kmcgill88** [comment]
🚀 https://pub.dev/packages/admob_flutter/versions/1.0.0-beta.5

**Comment by anderspetersson** [comment]
Sorry to comment on a closed issue, but I'm experiencing the same issue on Android and version 1.0.0-beta.5

Any plans to apply the same fix to Android?
