### ISSUE TITLE
Ad failed to load : 1

### ISSUE THREAD

**Issue by akmalviya03** [kmcgill88/admob_flutter#187]
Getting This error In android SDK version 28 with AndroidX compatibility. Widget Was working Fine with The testUnitId. But Not WIth my Ad unit. I 

AdmobBanner(
                adUnitId: 'myId',
                adSize: AdmobBannerSize.BANNER,
              ),

**Comment by kmcgill88** [comment]
Error Code 1 : ERROR_CODE_INVALID_REQUEST
The ad request was invalid; for instance, the ad unit ID was incorrect.

This commonly suggests that the Ad Request implementation is not as per the SDK’s requirements - Resources like the  sample codes and sample apps provided in the developer documentation can help in implementing the functions correctly.

https://support.google.com/admob/thread/3494603?hl=en

Also checkout, https://github.com/kmcgill88/admob_flutter#faq

**Comment by akmalviya03** [comment]
The ad unit Id is correct, I have tested that Ad Unit Id with firebaseadmob package provided by Google. By the way, plugin Is useful. Thank you for giving us this type of plugin. I hope you will fix this bug soon.

**Comment by kmcgill88** [comment]
@akmalviya03 this isn’t a bug with this package. Is your app id correct too? You should have app id for iOS and another for android. Same for unit ids.

**Comment by akmalviya03** [comment]
@kmcgill88 yes, app id is also correct. I am only developing an application for android using flutter. Does this plugin require iOS configuration for AdMob?

**Comment by EliasDeuss** [comment]
@akmalviya03 I believe it does (if I remember correctly).

**Comment by kmcgill88** [comment]
@akmalviya03 you should be able to run android only and skip iOS config if you don’t use it
