### ISSUE TITLE
iOS 14 Beta, error

### ISSUE THREAD

**Issue by thesmartrenovation** [kmcgill88/admob_flutter#189]
Hi

In the iOS 14 beta the ads are not shown in the applications that are already published in the AppStore. 

How can I fix this problem?

**Comment by EliasDeuss** [comment]
@thesmartrenovation Could be a flutter issue with the package or a package issue. Flutter currently doesn't fully support iOS 14 yet (As it has only come out about a week and a half ago. @kmcgill88 We might have to do some testing to see exactly what is casing the issue.

**Comment by kmcgill88** [comment]
I'm not overly worried about this. The public release of iOS 14 is a few months out still. I think we just need to keep an eye on this and see what Flutter does to fully support 14.

**Comment by vegidio** [comment]
@kmcgill88 I just created a new issue #208 addressing this. This is related to the new framework that Apple added regarding tracking ads. But it seems that Google already worked on a solution for this issue on version 7.64 of their Mobile Ads SDK.

So, **in theory**, we just need to upgrade `admob_flutter` to use GMA SDK version 7.64 and ads should work again on iOS 14.

**Comment by kmcgill88** [comment]
This is addressed in #208
