### ISSUE TITLE
How to add a testDevice id's to test the ads in real device?

### ISSUE THREAD

**Issue by johng2t** [kmcgill88/admob_flutter#196]
I initialize the AdMob and with the appId, But I can't add testDeviceId's to test the ads in devices.
 ` Admob.initialize(getAppId());`
![image](https://user-images.githubusercontent.com/46560005/87761310-dd980600-c82e-11ea-9c10-8eb8e1a735b6.png)

Please advice on how to add testDevice and test the ads.

**Comment by felixgabler** [comment]
You need to be using the ^1.0.0-beta.5 version. The method signature changed from 0.3.x to 1.x

**Comment by johng2t** [comment]
> You need to be using the ^1.0.0-beta.5 version. The method signature changed from 0.3.x to 1.x

Sorry for not update my answer here, I have resolved it by switching to beta-version
