### ISSUE TITLE
[Question] How do I make the "onClick" or "onTab" in the banner work?

### ISSUE THREAD

**Issue by Cubel89** [kmcgill88/admob_flutter#202]
I have managed to make the Banner show without any problem. But I can't get it to work properly because when the ad is clicked, nothing happens. Yours would be to open the advertiser's website, am I right?

**Comment by ADIBzTER** [comment]
Have you checked whether the ads underlay of other invisible widgets?

**Comment by Cubel89** [comment]
To test, I have created an empty page with a Wigdet Center and inside the Widget the banner and still does not detect the click

**Comment by ADIBzTER** [comment]
May you share your code here?

**Comment by Cubel89** [comment]
Yes of course. In an hour or so I can get home and copy the code.

I'm thinking there can be two things ...

1, I am testing on the latest version of Android and the same emulator ...

2, you may have some "consumer <Provider>" at materialAPP level.
