### ISSUE TITLE
A problem occurred configuring root project 'admob_flutter'.

### ISSUE THREAD

**Issue by dhimant1990** [kmcgill88/admob_flutter#203]
* What went wrong:
A problem occurred configuring root project 'admob_flutter'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by kmcgill88** [comment]
This looks like more of an Android + gradle issue than admob_flutter. I'd run a flutter clean and build again.

**Comment by kmcgill88** [comment]
@dhimant1990 Did you solve this?

**Comment by dhimant1990** [comment]
Yes, I resolved

I only updated my android app icon, and this issue was resolved
