### ISSUE TITLE
Module 'admob_flutter' not found

### ISSUE THREAD

**Issue by chamodaranasinghe** [kmcgill88/admob_flutter#207]
App run successfully in debug and release mode. But when trying to build using Xcode or Archive using Xcode, Build failed with this error.

ios/Runner/GeneratedPluginRegistrant.m:10:9: Module 'admob_flutter' not found

flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.1 at /Users/sd/Documents/DevTools/flutter
    • Framework revision 2ae34518b8 (11 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone (mobile) • 2620913a0d5e6787744110faa95c39a2fedb0887 • ios • iOS 13.5.1

**Comment by dikdableu** [comment]
could you give us how do you solve the issue

**Comment by chamodaranasinghe** [comment]
It was my mistake. I opened Runner.xcodeproj instead of Runner.xcworkspace. Open Runner.xcworkspace, and build.
