### ISSUE TITLE
Upgrade Google Mobile Ads SDK to version 7.64 to support iOS 14

### ISSUE THREAD

**Issue by vegidio** [kmcgill88/admob_flutter#208]
Apple will release a new transparency framework on iOS 14 that will prevent the ads to be shown if the app is not using at least version 7.64 of Google Ads SDK. The current version used by `admob_flutter` is 7.59.

More info can be found here: https://support.google.com/admob/answer/9997589

**Comment by Skyost** [comment]
I'm gonna submit a pull request to fix this one.

**Comment by EmiiFont** [comment]
why is the pull request not accepted yet?

**Comment by Skyost** [comment]
@EmiiFont They need to review it (and add to that that Xcode 12 is required to compile it).

**Comment by kmcgill88** [comment]
@EmiiFont, (un)fortunately I have a full-time day job. I do this project on the side, as time allows. I will review this today, make sure the build is passing and publish a new version ASAP.
