### ISSUE TITLE
flutter build ios release error

### ISSUE THREAD

**Issue by teenking** [kmcgill88/admob_flutter#210]
Dear Sir,
I have the errors while i build ios app.
Please see detail:

Xcode's output:
↳
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:25:35: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        fileprivate var allIds: [Int: GADRewardBasedVideoAd] = [:]
                                      ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:93:52: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        private func getRewardBasedVideoAd(id: Int) -> GADRewardBasedVideoAd {
                                                       ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:110:51: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAd(_ rewardBasedVideoAd: GADRewardBasedVideoAd, didRewardUserWith reward: GADAdReward) {
                                                      ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:117:58: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidOpen(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                             ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:121:59: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidClose(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                              ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:125:61: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidReceive(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:129:66: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidStartPlaying(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                     ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:133:68: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdMetadataDidChange(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                       ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:137:69: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidCompletePlaying(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                        ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:141:71: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdWillLeaveApplication(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                          ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:145:51: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAd(_ rewardBasedVideoAd: GADRewardBasedVideoAd, didFailToLoadWithError error: Error) {
                                                      ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:95:38: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
                let rewardBadedVideoAd = GADRewardBasedVideoAd.sharedInstance()
                                         ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:25:35: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        fileprivate var allIds: [Int: GADRewardBasedVideoAd] = [:]
                                      ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:93:52: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        private func getRewardBasedVideoAd(id: Int) -> GADRewardBasedVideoAd {
                                                       ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:110:51: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAd(_ rewardBasedVideoAd: GADRewardBasedVideoAd, didRewardUserWith reward: GADAdReward) {
                                                      ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:117:58: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidOpen(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                             ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:121:59: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidClose(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                              ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:125:61: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidReceive(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:129:66: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidStartPlaying(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                     ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:133:68: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdMetadataDidChange(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                       ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:137:69: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdDidCompletePlaying(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                        ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:141:71: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAdWillLeaveApplication(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                          ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:145:51: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
        func rewardBasedVideoAd(_ rewardBasedVideoAd: GADRewardBasedVideoAd, didFailToLoadWithError error: Error) {
                                                      ^
    /Users/teen/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.4/ios/Classes/AdmobRewardPlugin.swift:95:38: warning: 'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead.
    Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here:
    https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.
                let rewardBadedVideoAd = GADRewardBasedVideoAd.sharedInstance()

**Comment by kmcgill88** [comment]
Try again with version `1.0.0` and Xcode 12.

**Comment by teenking** [comment]
> Try again with version `1.0.0` and Xcode 12.

It's work!
Thank you so much.
