### ISSUE TITLE
My banner ad isnt loading

### ISSUE THREAD

**Issue by jabguru** [kmcgill88/admob_flutter#213]
I've done all the necessary setup, added the app id to manifest, connected the app to firebase but i get this error

I/Ads     (12815): Ad failed to load : 3

Please help me out

**Comment by Skyost** [comment]
@jabguru See the second item of the [FAQ](https://github.com/kmcgill88/admob_flutter#faq).

**Comment by jabguru** [comment]
Solved. I just had to wait.
