### ISSUE TITLE
Not compatible with latest Firebase packages upgrade

### ISSUE THREAD

**Issue by pazhut** [kmcgill88/admob_flutter#214]
Hi

i had updated to latest firebase_auth and firebase_storage packages and i am getting the following error on dependencies:[!] CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 0.3.4, which depends on
      FirebaseAnalytics (~> 6.1.3) was resolved to 6.1.3, which depends on
        nanopb (~> 0.3.901)

    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.18.0-1, which depends on
      Firebase/Auth (~> 6.26.0) was resolved to 6.26.0, which depends on
        FirebaseAuth (~> 6.5.3) was resolved to 6.5.3, which depends on
          FirebaseCore (~> 6.6) was resolved to 6.7.2, which depends on
            FirebaseCoreDiagnostics (~> 1.3) was resolved to 1.6.0, which depends on
              nanopb (~> 1.30906.0)

Can you help with upgrading your plugin to match latest firebase versions

Thanks much

**Comment by kmcgill88** [comment]
@pazhut try using one of the pre-release versions like `1.0.0-beta.6`

**Comment by praharshbhatt** [comment]
Similar issue here:

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Auth":
  In snapshot (Podfile.lock):
    Firebase/Auth (= 5.20.2, ~> 5.19)

  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.18.0-1, which depends on
      Firebase/Auth (~> 6.26.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Firebase/Auth` inside your development pod `firebase_auth`.
   You should run `pod update Firebase/Auth` to apply changes you've made.
```

My firebase dependencies:


```
  firebase_dynamic_links: ^0.6.0
  firebase_messaging: ^7.0.0
  firebase_in_app_messaging: ^0.2.0+1
  apple_sign_in: ^0.1.0
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
```

**Comment by kmcgill88** [comment]
Have you tried what the error suggested?

Also may need to run flutter clean.

**Comment by pazhut** [comment]
Tried all of this nothing works, you will need to update your plugin to
match other firebase plugins

Thanks

**Comment by karthikjn01** [comment]
I am having the same issue. My issue is with the analytics, here is the error:
`
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 1.0.0-beta.5, which depends on
      Firebase/Analytics (~> 6.30)

    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 6.0.0, which depends on
      Firebase/Analytics (~> 6.26.0)
`
@kmcgill88 is there a work around for the moment? What firebase plugin version will work with your latest plugin version?

**Comment by kmcgill88** [comment]
@karthikjn01 what does your environment look like? I don't know of a work around off th top of my head. If you igure one out PR's welcome.

**Comment by felixgabler** [comment]
> I am having the same issue. My issue is with the analytics, here is the error:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
>   In Podfile:
>     admob_flutter (from .symlinks/plugins/admob_flutter/ios) was resolved to 1.0.0-beta.5, which depends on
>       Firebase/Analytics (~> 6.30)
> 
>     firebase_analytics (from .symlinks/plugins/firebase_analytics/ios) was resolved to 6.0.0, which depends on
>       Firebase/Analytics (~> 6.26.0)
> ```
> 
> @kmcgill88 is there a work around for the moment? What firebase plugin version will work with your latest plugin version?

I have the exact same problem

**Comment by kmcgill88** [comment]
I added 

```
firebase_dynamic_links: ^0.6.0
  firebase_messaging: ^7.0.0
  firebase_in_app_messaging: ^0.2.0+1
  apple_sign_in: ^0.1.0
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
```

to the example app and `flutter pub get` worked fine. 😕 

I'll do some more testing.

Maybe try these steps?
- ` flutter clean`
-  Delete `Podfile.lock` in ios folder
- `flutter run`

**Comment by sharokh1** [comment]
It is not working for me..

`    [!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
      In Podfile:
        admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 1.0.0-beta.6, which depends on
          Firebase/Analytics (~> 6.30)

        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 6.0.0, which depends on
          Firebase/Analytics (~> 6.26.0)

    CocoaPods could not find compatible versions for pod "FirebaseCore":
      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 6.0.0, which depends on
          Firebase/CoreOnly (~> 6.26.0) was resolved to 6.26.0, which depends on
            FirebaseCore (= 6.7.2)

        firebase_dynamic_links (from `.symlinks/plugins/firebase_dynamic_links/ios`) was resolved to 0.6.0, which depends on
          Firebase/DynamicLinks (~> 6.26.0) was resolved to 6.26.0, which depends on
            FirebaseDynamicLinks (~> 4.0.8) was resolved to 4.0.8, which depends on
              FirebaseCore (~> 6.2)

`

**Comment by reijerteunis** [comment]
@sharokh1 thanks a lot this worked.

Can we fix this in the next version?
I wonder is this module ready for iOS 14

**Comment by Toolenaar** [comment]
Having this issue aswell, tried all the options above to fix it but this does not work for my configuration. I use almost all firebase services in my app. Any ETA on an update of the package?

**Comment by kmcgill88** [comment]
I was able to reproduce this on a small app of mine. I will keep working the issue and 

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
      In snapshot (Podfile.lock):
        Firebase/Analytics (= 6.24.0, ~> 6.0, ~> 6.5)
      In Podfile:
        admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 1.0.0-beta.5, which depends on
          Firebase/Analytics (~> 6.30)
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 6.0.0, which depends on
          Firebase/Analytics (~> 6.26.0)
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `Firebase/Analytics` inside your development pod `firebase_analytics`.
       You should run `pod update Firebase/Analytics` to apply changes you've made.
```

@sharokh1 glad you found a work-a-round!


@Skyost I see the ios analytics version was lowered in [this commit](https://github.com/kmcgill88/admob_flutter/commit/d496bd011e8a4e63fff56903c2a346f0b4ed4fe6#diff-74ff245657658c37fa9ea3db1de745a8R21) I wonder if we can just leave off the version for `Firebase/Analytics`? I'll give it a try.

**Comment by Skyost** [comment]
@kmcgill88 In fact, while updating `Google-Mobile-Ads-SDK` I also updated `Firebase/Analytics` at the same time (so that all dependencies are up-to-date). But those are independant, so I think you can downgrade `Firebase/Analytics` without any problem.

**Comment by kmcgill88** [comment]
For those who can't wait this is the commit that has an open PR.

```
  admob_flutter:
    git:
      url: git@github.com:kmcgill88/admob_flutter.git
      ref: 8a554916eaa57b3ed303efe797e466bd6ccf79a8
```

it will be rolled to beta 7 when all ci checks out ✅

**Comment by SoftWyer** [comment]
And a slightly different url syntax for those struggling with the above:
```
  admob_flutter:
    git:
      url: git://github.com/kmcgill88/admob_flutter.git
      ref: 8a554916eaa57b3ed303efe797e466bd6ccf79a8
```

**Comment by kmcgill88** [comment]
Added [PR comment](https://github.com/kmcgill88/admob_flutter/pull/216/files#r483951395) as a post-mortem of the issue.

**Comment by kmcgill88** [comment]
[Beta 7](https://pub.dev/packages/admob_flutter/versions/1.0.0-beta.7) is available now!

**Comment by dynacorp** [comment]
<img width="1000" alt="Screen Shot 2020-09-05 at 4 26 40 PM" src="https://user-images.githubusercontent.com/20915993/92308310-a7584680-ef94-11ea-8edf-108ecbb9f3d9.png">
getting this error when running building ios

**Comment by SoftWyer** [comment]
> <img alt="Screen Shot 2020-09-05 at 4 26 40 PM" width="1000" src="https://user-images.githubusercontent.com/20915993/92308310-a7584680-ef94-11ea-8edf-108ecbb9f3d9.png">
> 
> getting this error when running building ios

I believe this needs [Xcode 12 (beta)](https://developer.apple.com/download/) to resolve this. At least that was one of the steps I took, along with making sure Crashlytics was updated to the latest beta too.

**Comment by Skyost** [comment]
> @dynacorp : getting this error when running building ios

SoftWyer is right, you need Xcode 12 to build the latest versions. It's written in the [changelog](https://pub.dev/packages/admob_flutter/versions/1.0.0-beta.7/changelog#100-beta6---20200831). I can only suggest you to wait for the official release of Xcode 12 (should happen at mid / end of september) before updating to the latest Betas of this plugin.

> @SoftWyer : Is it me or is developing for Apple really painful?

It's not you, it's painful (and expensive) to develop for Apple systems, especially for iOS (although I think they're in the right path with Swift). But Google have their downsides too, eh, just search for "ban" or /r/android_devs.

I think it's more complicated to develop for iOS, but once you finished your product, you know you will have some support from Apple afterward. But with Flutter and its package ecosystem there's not so much difference between developing for iOS and for Android (well, if you don't use platform channels).

**Comment by HzKurdi** [comment]
> I added
> 
> ```
> firebase_dynamic_links: ^0.6.0
>   firebase_messaging: ^7.0.0
>   firebase_in_app_messaging: ^0.2.0+1
>   apple_sign_in: ^0.1.0
>   firebase_core: ^0.5.0
>   firebase_analytics: ^6.0.0
>   firebase_auth: ^0.18.0+1
> ```
> 
> to the example app and `flutter pub get` worked fine. 😕
> 
> I'll do some more testing.
> 
> Maybe try these steps?
> 
>     * ` flutter clean`
> 
>     * Delete `Podfile.lock` in ios folder
> 
>     * `flutter run`

It Worked good, Thanks

**Comment by pazhut** [comment]
Release 1.0.0 work good
