### ISSUE TITLE
Does admob_flutter support ad mediation?

### ISSUE THREAD

**Issue by Arie290698** [kmcgill88/admob_flutter#217]
I'm using admob_flutter as an ad viewer for my app, and I'm trying to use the mediation feature in Admob. But the result is not a single advertisement that is displayed from the mediation.
So I thought "looks like admob_flutter doesn't support mediation". But I like admob_flutter more than other plugins, so I hope you can add a mediation feature.

**Comment by Arie290698** [comment]
After I tried it, admob_flutter supports mediation.

**Comment by oGranny** [comment]
Can you please tell how did you enable mediation

**Comment by oGranny** [comment]
@Arie290698 can you please tell how to enable mediation

**Comment by Arie290698** [comment]
> @Arie290698 can you please tell how to enable mediation
@oGranny 
First of all you have to install the SDK for each ad network. You can see it here https://developers.google.com/admob/android/mediate
After you install it, you only need to set it through the mediation panel on AdMob.

If you are not sure whether your mediation is working or not, you can check it using this plugin https://pub.dev/packages/mediation_test

**Comment by onstonboy** [comment]
> > @Arie290698 can you please tell how to enable mediation
> > @oGranny
> > First of all you have to install the SDK for each ad network. You can see it here https://developers.google.com/admob/android/mediate
> > After you install it, you only need to set it through the mediation panel on AdMob.
> 
> If you are not sure whether your mediation is working or not, you can check it using this plugin https://pub.dev/packages/mediation_test

Hi, as you say so you just need to add mediation in AdMob website and do nothing in code right?
