### ISSUE TITLE
test device ids

### ISSUE THREAD

**Issue by faisal-ismail** [kmcgill88/admob_flutter#220]
there is no option for adding test device ids for testing purposes.

**Comment by nixxxon** [comment]
Hi,

It seems to be missing from the README but check the example: 
https://github.com/kmcgill88/admob_flutter/blob/97003f89ec9115503fe26d9ebe4bf095512bbd95/example/lib/main.dart#L15

**Comment by machkonti** [comment]
And yet there is no option to add test devices ...

'admob.dart'
import 'package:flutter/services.dart';

class Admob {
  Admob.initialize(String appId) {
    MethodChannel _channel = const MethodChannel('admob_flutter');
    _channel.invokeMethod('initialize', appId);
  }
}

**Comment by pav3lo** [comment]
> Hi,
> 
> It seems to be missing from the README but check the example:
> 
> https://github.com/kmcgill88/admob_flutter/blob/97003f89ec9115503fe26d9ebe4bf095512bbd95/example/lib/main.dart#L15

That is not possible: it just support for appId, no testDevicesId   
Admob.initialize(appId);

**Comment by nixxxon** [comment]
> > Hi,
> > It seems to be missing from the README but check the example:
> > https://github.com/kmcgill88/admob_flutter/blob/97003f89ec9115503fe26d9ebe4bf095512bbd95/example/lib/main.dart#L15
> 
> That is not possible: just support for appId, no testDevicesId
> Admob.initialize(appId);
> 
> How to set the test device ids?

Looks like it was added in `1.0.0-beta.3`: 
https://github.com/kmcgill88/admob_flutter/commit/6ce5a9451c2f19fd9342c80610c0dd779aa3ea66

**Comment by kmcgill88** [comment]
Correct, `Admob.initialize(testDeviceIds: ['YOUR DEVICE ID']); ` if you want to use test devices and `Admob.initialize();`  if not. Version `1.0.0` is now published.
