### ISSUE TITLE
Banners not shown and Reward "completed" not called ONLY IN IOS

### ISSUE THREAD

**Issue by roishu** [kmcgill88/admob_flutter#226]
version 1.0.0

In android everything is perfect,

But in ios banners is not shown. 

(in debug and in release, our app called "Teammate - find your teammate" in appstore you can check)

In addition in reward add, only "rewarded" event is happend and when the add is finished "completed" event does not called.

this 2 issues happend only in ios.

**Comment by roishu** [comment]
![WhatsApp Image 2020-09-28 at 21 11 16](https://user-images.githubusercontent.com/11149460/94471226-7654e580-01d1-11eb-80f1-9a2998cddf79.jpeg)

here's what I see in ios debug (banner not shown)

**Comment by efraespada** [comment]
Same problem here

**Comment by roishu** [comment]
In my situation unchecking "Limit Ad Tracking" also not solve my problem.
I also open an issue to admob, and they didn't answer yet :(

**Comment by roishu** [comment]
**Solved It !**
Excidently I put this key with wrong spelling 
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

**Comment by kmcgill88** [comment]
If you are using flutter 1.22 apparently, that isn't required anymore. I haven't tested it yet but the 1.22 changelog mentions it.
