### ISSUE TITLE
When app is offline , it takes space of banner size 

### ISSUE THREAD

**Issue by mahtoBabu** [kmcgill88/admob_flutter#229]
when app is offline it should not be take any space , how to solve it ?

**Comment by Octet83** [comment]
You can use listener (in widget) to check if there is AdmobAdEvent.failedToLoad event

**Comment by yardstick17** [comment]
@Octet83  It would be great if you can give a code sample to show this listener can be used. ( Fairly new to flutter)

**Comment by kmcgill88** [comment]
This isn't a plugin related issue. Closing.
