### ISSUE TITLE
Only release iOS : Flutter: Admob banner failed to load. Error code:1 

### ISSUE THREAD

**Issue by Naografix** [kmcgill88/admob_flutter#233]
Hello

I got this problem since 3 weeks and even after publishing my iOS app on the Apple Store, I got this error and I don't understand why...

I followed all your "tuto" and I can't fix my problem.

![image](https://user-images.githubusercontent.com/6979203/98452131-d33aa880-214c-11eb-9e37-a4f948a5589d.png)

![image](https://user-images.githubusercontent.com/6979203/98452199-67a50b00-214d-11eb-8cba-52bd5a97e41f.png)

SettingsHelper()
```
void _loadAd() async {
    if (SettingsHelper().isAndroid) {
        pageLoaded = true;
    } else {
        pageLoaded = await Admob.requestTrackingAuthorization();
    }
    setState(() => pageLoaded);
}
```

My page.dart
```
child: Stack(children: [
  currentWidget,
  if (pageLoaded)
    Align(
      alignment: Alignment.bottomCenter,
      child: AdmobBanner(
        listener: (AdmobAdEvent event, Map<String, dynamic> args) {
          switch (event) {
            case AdmobAdEvent.loaded:
              print("loaded");
              break;
            case AdmobAdEvent.opened:
              print("opened");
              break;
            case AdmobAdEvent.closed:
              print("closed");
              break;
            case AdmobAdEvent.failedToLoad:
              print("Admob banner failed to load. Error code: ${args['errorCode']}");
              break;
            case AdmobAdEvent.clicked:
              print("clicked");
              break;
            case AdmobAdEvent.impression:
              print("impression");
              break;
            case AdmobAdEvent.leftApplication:
              print("leftApplication");
              break;
            case AdmobAdEvent.completed:
              print("completed");
              break;
            case AdmobAdEvent.rewarded:
              print("rewarded");
              break;
            case AdmobAdEvent.started:
              print("started");
              break;
          }
        },
        adUnitId: SettingsHelper().getAdToken(),
        adSize: AdmobBannerSize.BANNER,
      ),
    )
]),
```

Thank you for your help

**Comment by steirersoft** [comment]
i had the same error. After i could link my Admob project with the app store it worked.

**Comment by danielgchap** [comment]
> i had the same error. After i could link my Admob project with the app store it worked.

Thank you for being so ambiguous in your resolution. Really helpful. 👎

**Comment by Naografix** [comment]
> > i had the same error. After i could link my Admob project with the app store it worked.
> 
> Thank you for being so ambiguous in your resolution. Really helpful. 👎

Oops, I forgot to close this bug.
Indeed, you must link Apple to Admob (I waited 2 weeks after my first production release to see my app in Admob)

![image](https://user-images.githubusercontent.com/6979203/100255224-8bd15c00-2f43-11eb-8357-8bc1d528cc79.png)

**Comment by whiplashoo** [comment]
Same thing happened to me. 

Ads were showing up on Android (simulator, beta, and production) and iOS (simulator only). They didn't appear on TestFlight or on the published iOS app until I made the link to the App Store through the AdMob Settings (Google AdMob > App > App Settings > App Store).

Also, I had to wait 2-3 days after launching until I could find my app there and link it.

**Comment by bebe0612** [comment]
same to me.

**Comment by PSJMcNeill** [comment]
How long should it take after linking admob to the app store?

I've linked my app but still getting Error code: 1

But the Test Mode Ads show fine when running in debug

**Comment by Naografix** [comment]
> How long should it take after linking admob to the app store?
> 
> I've linked my app but still getting Error code: 1
> 
> But the Test Mode Ads show fine when running in debug

Approximately 1 month+ (something like that)

**Comment by danielgchap** [comment]
I've seen people say a few days. I haven't researched lately but I need to. If I find anything different I will post but I have consistently seen people say that with flutter apps, it takes a few days to get the ads to show. You're not alone in this for sure.

**Comment by danielgchap** [comment]
> > How long should it take after linking admob to the app store?
> > I've linked my app but still getting Error code: 1
> > But the Test Mode Ads show fine when running in debug
> 
> Approximately 1 month+ (something like that)

Can be a bit helpful...

https://support.google.com/admob/answer/9469204?hl=en
