### ISSUE TITLE
Beta iOS App Store Rejected

### ISSUE THREAD

**Issue by danielgchap** [kmcgill88/admob_flutter#241]
Reason:
```
_**Guideline 2.1 - Information Needed


We're looking forward to completing the review of your app, but we need more information to continue. Specifically, we noticed that your app uses the AppTrackingTransparency framework, but we haven't been able to locate the relevant AppTrackingTransparency permission requests.

While it is not required to implement AppTrackingTransparency at this time, we check to make sure the implementation is compliant with our guidelines when we detect the framework in an app.

Next Steps

If your app integrates AppTrackingTransparency, please indicate where in your app we can find the AppTrackingTransparency permission request.

If your app does not integrate AppTrackingTransparency, please indicate this information in the Review Notes section for each version of your app in App Store Connect when submitting for review.**_
```

I have the usage description in the plist for NSUserTrackingDescription. However, your instructions don't call for any code to be included in the iOS app delegate but instead call AdMob.requestTrackingAuthorization()

Maybe I should remove that and just put the ios version in?

**Comment by whiplashoo** [comment]
Did you also update your ios/Podfile by adding platform :ios, '9.0'?

I did the steps required in the ReadMe and my app passed App Review without issues. Do you see the tracking authorization dialog when you open the app? It should show up right when the app is launched.

**Comment by danielgchap** [comment]
> Did you also update your ios/Podfile by adding platform :ios, '9.0'?
> 
> I did the steps required in the ReadMe and my app passed App Review without issues. Do you see the tracking authorization dialog when you open the app? It should show up right when the app is launched.

Hi there! Thanks for replying.
I DO see the permission request when app starts up. 'Seems' to be working as it should.
I have this in podfile:

platform :ios, '11.0' but it was commented out (it wasn't, maybe i did a git stash or something?)
I'll try again and keep you posted!

Thank you!!!! Will update!

**Comment by danielgchap** [comment]
That was it! The only thing I changed was to uncomment that line in podfile.
Thank you!!
