### ISSUE TITLE
Admob Banner failed to load. :(

### ISSUE THREAD

**Issue by briankariuki** [kmcgill88/admob_flutter#242]
I've implemented the banner and test ads are showing on an emulator, but when I build for release and test the app on a real device, no ads are showing up.

I get this error in the console

`Admob Banner failed to load. :(`

**Comment by bebe0612** [comment]
same to me.

**Comment by thisisamank** [comment]
i am also getting the same error

**Comment by briankariuki** [comment]
for me it was that admob need first to detect traffic coming from your app to start serving real ads

**Comment by briankariuki** [comment]
Ads started showing up in my app 3 days ago after I shared it with some testers in the alpha stage.
closing this issue now
