### ISSUE TITLE
Error compiling IOS App

### ISSUE THREAD

**Issue by Rart3001** [kmcgill88/admob_flutter#246]
Hello, I am getting this error:

`
[!] CocoaPods could not find compatible versions for pod "admob_flutter":
  In Podfile:
    admob_flutter (from `.symlinks/plugins/admob_flutter/ios`)

Specs satisfying the `admob_flutter (from `.symlinks/plugins/admob_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.
`
I´m using:

`
  #Admob
  admob_flutter: ^1.0.1
`

**Comment by Blast06** [comment]
Did you find a solution?

**Comment by tobiasosDev** [comment]
Just add at the top of  the ios/Podfile,  `platform :ios, '9.0' `
