### ISSUE TITLE
How to add custom data for SSV

### ISSUE THREAD

**Issue by Zeynal7** [kmcgill88/admob_flutter#248]
Hello,

I want to do Server-Side verification with rewarded video ads. But I cannot set custom data (https://developers.google.com/admob/android/rewarded-video-ssv#custom_data). Is it possible with this plugin?

**Comment by Zeynal7** [comment]
Added PR for this. Hope it will be merged.

**Comment by it-one-mm** [comment]
Don't use admob_flutter. Just use firebase_admob, and it is reliable.

**Comment by Zeynal7** [comment]
firebase_admob crashes during reward callback of rewarded ad on iOS.  But this plugin works fine. So until google fix that issue, I have no other choice but to use this plugin

**Comment by Zeynal7** [comment]
Also, in firebase_admob plugin, they are using deprecated API for iOS side. But this plugin uses new one. In any case, this one looks better to me
