### ISSUE TITLE
App Crashes on launch when using admob_flutter

### ISSUE THREAD

**Issue by egyleader** [kmcgill88/admob_flutter#257]
my app crashes on launch without any error message in the debug console when adding this plugin .. 
I am sure that I added the admob app id to the  `AndroidManifest.xml` if that what you was thinking ,
I run the debugging on a real Device Huawei y9 2019 and an emulator with android jellybean and both crash on launch ..
Note : the vscode debugger is stuck on `installing build\app\outputs\flutter-apk\app.apk...`

this is the output of flutter doctor : 

> [√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Android Studio (version 3.5)
> [√] VS Code, 64-bit edition (version 1.52.1)
> [√] Connected device (1 available)
> 
> • No issues found!

**Comment by DanielTerbl** [comment]
Got the same issue.
