### ISSUE TITLE
Null safety handling

### ISSUE THREAD

**Issue by QuentinCG** [kmcgill88/admob_flutter#258]
Hello,

Thanks for this awesome package !

I just wanted to know if you'll migrate the package to handle null-safety (`sdk: '>=2.8.1 <3.0.0'`).

Here is the official dart explanation on what null-safety is and how to migrate:
https://dart.dev/null-safety/migration-guide

This is not a critical issue but it means this package is not handling a potentially good opportunity to prevent "null value" issues.

**Comment by kmcgill88** [comment]
I'm also very excited about null safety! I want this plugin to be null safe however I haven't had time to implement it. PR's are very much welcome! If you have time to tackle it; that would be great!
