### ISSUE TITLE
How to put an Admob banner ad inside a stateful widget that is rebuilt every second?

### ISSUE THREAD

**Issue by farazk86** [kmcgill88/admob_flutter#264]
I have a stateful widget that is rebuilt every second as it needs to update the screen every time a new word is generated by another script.

On this same screen I want to display an admob banner.

```dart
    child: Column(
              children: [
                AdmobBanner(
                  adUnitId: 'ca-app-pub-3940256099942544/6300978111',     //this is test id
                  adSize: AdmobBannerSize.FULL_BANNER,
                ),
              RichText(),                            // my other widget that is repopulated every second
    ..
    ..
```

Rebuilding the admob banner this often and sending this many requests to get a new banner will certainly get my account limited/banned. 

Is there any way I can get this done?

**Comment by QuentinCG** [comment]
Here is how I procede to not send too much request to admob:

```
class StaticAds {
  // Singleton
  static final StaticAds  _singleton = new StaticAds._internal();
  factory StaticAds() {
    return _singleton;
  }
  StaticAds._internal();


  AdmobBanner _localBanner; // Internal
  Widget getAdBannerWidget(...) {
    if (!(_localBanner is AdmobBanner)) {
        _localBanner = AdmobBanner(adUnitId: BLABLA, adSize: BLABLA);
    }
    return _localBanner;
  }
```

Then call the `StaticAds().getAdBannerWidget()` function from your stateful widget

**Comment by farazk86** [comment]
> Here is how I procede to not send too much request to admob:
> 
> ```dart
> class StaticAds {
>   // Singleton
>   static final StaticAds  _singleton = new StaticAds._internal();
>   factory StaticAds() {
>     return _singleton;
>   }
>   StaticAds._internal();
> 
> 
>   AdmobBanner _localBanner; // Internal
>   Widget getAdBannerWidget(...) {
>     if (!(_localBanner is AdmobBanner)) {
>         _localBanner = AdmobBanner(adUnitId: BLABLA, adSize: BLABLA);
>     }
>     return _localBanner;
>   }
> ```
> 
> Then call the `StaticAds().getAdBannerWidget()` function from your stateful widget

This is beautiful and exactly what I wanted to do. Thank you :)

**Comment by QuentinCG** [comment]
You are welcome ;)
