### ISSUE TITLE
Missing testIds from 2.0.0-nullsafety.0

### ISSUE THREAD

**Issue by jagomf** [kmcgill88/admob_flutter#273]
Static `testAdUnitId` is missing from latest `2.0.0-nullsafety.0` release as recently [pointed out in the initial PR](https://github.com/kmcgill88/admob_flutter/pull/227#issuecomment-804263209).

![image](https://user-images.githubusercontent.com/4032522/112034089-67c30780-8b3e-11eb-81fc-a1aa24d3f081.png)
![image](https://user-images.githubusercontent.com/4032522/112033990-48c47580-8b3e-11eb-8e3d-329eebbef6dc.png)

**Comment by armandojimenez** [comment]
same problem

**Comment by jagomf** [comment]
@kmcgill88 is this planned for a `2.0.0-nullsafety.1` or any other release anytime soon?
Thanks
