### ISSUE TITLE
App crashes on startup for firebase_admob dependency 0.8.0+4

### ISSUE THREAD

**Issue by Azhankhan03** [kmcgill88/admob_flutter#28]
I was using fiirebase_admob dependency 0.5.5 which was working great but when I went to release the apk version by flutter build apk --release it gave me error so I had to change the dependency from 0.5.5 to 0.8.0+4 and add API 'com.google.firebase:firebase-ads:16.0.1' in dependency of build>gradle this gave me the app-release.apk but causing app is crashing on startup.
I am getting the error during flutter build apk for dependency firebase_admob- 0.5.5, but it runs perfectly on run command  but when I use 0.8.0+4 dependency the app crashes on startup but I am getting the apk. So, what should I change my dependency to get the app running smoothly?

The error on terminal during flutter build for dependency 0.5.5 is-

* What went wrong:
Execution failed for task ':firebase_admob:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\Users\Azhan Khan\AndroidStudioProjects\simple_motivation\build\firebase_admob\intermediates\res\merged\release\values\values.xml:304: error: resource android:attr/fontVariationSetti
ngs not found.
  C:\Users\Azhan Khan\AndroidStudioProjects\simple_motivation\build\firebase_admob\intermediates\res\merged\release\values\values.xml:305: error: resource android:attr/ttcIndex not found
.
  error: failed linking references.

**Comment by kmcgill88** [comment]
firebase_admob is a different project than this repo. Did you intend to create this issue here?

**Comment by EliasDeuss** [comment]
@Azhankhan03 I think you have mistaken the repo, this is not the repo for firebase_admob . Closing this issue, please reopen this if you think this is wrong.
