### ISSUE TITLE
  [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":

### ISSUE THREAD

**Issue by penguru** [kmcgill88/admob_flutter#283]
I'm getting following error while using together with firebase_analytics.

```
    [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In Podfile:
        admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 1.0.0, which depends on
          Google-Mobile-Ads-SDK (~> 7.64) was resolved to 7.67.0, which depends on
            GoogleAppMeasurement (~> 6.0)

        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 8.1.2, which depends on
          Firebase/Analytics (= 8.0.0) was resolved to 8.0.0, which depends on
            Firebase/Core (= 8.0.0) was resolved to 8.0.0, which depends on
              FirebaseAnalytics (~> 8.0.0) was resolved to 8.0.0, which depends on
                FirebaseAnalytics/AdIdSupport (= 8.0.0) was resolved to 8.0.0, which depends on
                  GoogleAppMeasurement (= 8.0.0)
```

**Comment by marcellocamara** [comment]
Same error here.
I think ther`s something in conflict with this versions:
```
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  firebase_crashlytics: ^2.0.6
  admob_flutter: ^2.0.0-nullsafety.1
```

**Comment by rafagan** [comment]
Same problem. Any work in progress on that?

**Comment by admincode1** [comment]
1+

**Comment by Pilaba** [comment]
+1

**Comment by MartinJLee** [comment]
I don't know how other people are handling this. I ended up switch to https://pub.dev/packages/google_mobile_ads
Just need to add to `ios/Runner/Info.plist` see https://github.com/googleads/googleads-mobile-flutter#update-your-infoplist
```
<key>SKAdNetworkItems</key>
  <array>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>cstr6suwn9.skadnetwork</string>
    </dict>
  </array>
```

Following is my wrapper class that could simply replace `admob_flutter` widget.
```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class AdWidgetWrapper extends StatefulWidget {
  final AdSize size;
  final String adUnitId;
  final BannerAdListener listener;
  final AdRequest request;

  const AdWidgetWrapper(
      {Key key, this.size, this.adUnitId, this.listener = const BannerAdListener(), this.request = const AdRequest()})
      : super(key: key);

  @override
  _AdWidgetWrapperState createState() => _AdWidgetWrapperState();
}

class _AdWidgetWrapperState extends State<AdWidgetWrapper> {
  BannerAd _banner;

  @override
  void initState() {
    super.initState();
    _banner =
        BannerAd(size: widget.size, adUnitId: widget.adUnitId, listener: widget.listener, request: widget.request);
    _banner.load();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: AdWidget(
        ad: _banner,
      ),
      width: _banner.size.width.toDouble(),
      height: _banner.size.height.toDouble(),
    );
  }
}
```

If you need `Adaptive Banner` the following code can help you.
```dart
FutureBuilder<AnchoredAdaptiveBannerAdSize>(
  future: AdSize.getAnchoredAdaptiveBannerAdSize(Orientation.portrait, Get.width.truncate()),
  builder: (BuildContext context, AsyncSnapshot<AnchoredAdaptiveBannerAdSize> snapshot) {
    if (snapshot.connectionState == ConnectionState.done && snapshot.hasData) {
      return AdWidgetWrapper(adUnitId: AdManager.signInRequired, size: snapshot.data);
    }
    return Container();
  });
```
Hope this can help others while the maintainers fix the ios dependency issue.

**Comment by Pilaba** [comment]
I already try google_mobile_ads and even though is maintained by the google team

The plugin has a massive performance issue with apps below android 10
see [https://github.com/googleads/googleads-mobile-flutter/issues/189](url)

That's why this plugin is a life saver rn, hope someone finds a workaround soon.

**Comment by Tetsukick** [comment]
Same problem. Any work in progress on that?

**Comment by tommienu** [comment]
As an interim solution, you can edit .symlinks/plugins/admob_flutter/ios/admob_flutter.podspec and set `s.dependency 'Google-Mobile-Ads-SDK'` to 8.3.0 and it will compile.

``` s.dependency 'Google-Mobile-Ads-SDK', '~> 7.64' ```
  
Your milage may vary and things might break. But this "fix" allows me to continue to develop my app on iOS while we wait for a proper fix from @kmcgill88.

**Comment by davidgalarza** [comment]
Any work in progress on that? 😢

**Comment by marcellocamara** [comment]
I believe this package has been abandoned when firebase launch his own, on march 2021
Unfortunately, we depend on support to continue using it

So, let's migrate :pleading_face:

**Comment by kmcgill88** [comment]
> I believe this package has been abandoned when google launch his own, on march 2021
> 
> Unfortunately, we depend on support to continue using it
> 
> 
> 
> So, let's migrate :pleading_face:

I recommend moving to the official package. I really don't see a reason to keep this plug-in going when google has an officially sponsored one. Unless of course there is something I'm missing?

**Comment by davidgalarza** [comment]
The official package has a lot of bugs.

**Comment by kmcgill88** [comment]
> The official package has a lot of bugs. 

If any of you are interested I can add you as a maintainer and prs are always welcome. I just haven't had much time to keep up on this project by myself.

**Comment by marcellocamara** [comment]
> The official package has a lot of bugs.


I've migrated to official [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) and can confirm that the package have a lot of bugs (I've launched my app into production).
The major problem is the memory leak... When scroll the fps goes down.

Reading the opened issues at google_mobile_ads, users recommend [native_admob_flutter](https://pub.dev/packages/native_admob_flutter).

I really like this package here, but unfortunately I can't help updating it.

**Comment by penguru** [comment]
I'm currently using official package from Google without any issue.

**Comment by kmcgill88** [comment]
This should be resolved in the latest release.
