### ISSUE TITLE
After upgrading to flutter 3,i can't build my app this error message keep coming up

### ISSUE THREAD

**Issue by mohamedMesalm** [kmcgill88/admob_flutter#294]
/Users/pc/development/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-2.0.0/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBannerFactory.kt: (9, 1): Class 'AdmobBannerFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /Users/pc/development/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-2.0.0/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBannerFactory.kt: (10, 3): 'create' overrides nothing
e: /Users/pc/development/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-2.0.0/android/src/main/kotlin/com/shatsy/admobflutter/AdmobInterstitial.kt: (63, 29): Null can not be a value of a non-null type String
e: /Users/pc/development/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-2.0.0/android/src/main/kotlin/com/shatsy/admobflutter/AdmobReward.kt: (66, 29): Null can not be a value of a non-null type String
../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:167:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.

**Comment by IKRAMULHAQ786** [comment]
I am also facing the same issue. Waiting for an update of Admob flutter

**Comment by IKRAMULHAQ786** [comment]
@mohamedMesalm  did you find any solution yet...?

**Comment by kmcgill88** [comment]
I'm no longer maintaining this plugin in favor of the official google plugin.

If either of you come up with a fix I can add you as a maintainer so you can publish updates.

**Comment by pavelsust** [comment]
> I'm no longer maintaining this plugin in favor of the official google plugin.
> 
> If either of you come up with a fix I can add you as a maintainer so you can publish updates.

I want to maintain this repo already I have added Flutter 3.0 support and send you a pull request.

**Comment by pavelsust** [comment]
You can use this repo, issued are solved here

admob_flutter:
    git:
      url: https://github.com/pavelsust/admob_flutter

**Comment by kmcgill88** [comment]
@pavelsust  added you as a maintainer.

**Comment by pavelsust** [comment]
> @pavelsust added you as a maintainer.

thanks

**Comment by kmcgill88** [comment]
oh and share your email to publish pub.dev updates.

**Comment by pavelsust** [comment]
My user name is pavelsust

**Comment by pavelsust** [comment]
How I can update pub.dev version?

**Comment by pavelsust** [comment]
Did you add me into bitrise?

**Comment by pavelsust** [comment]
> I am also facing the same issue. Waiting for an update of Admob flutter

We have added 3.0 support you can use it now.
