### ISSUE TITLE
iOS side need update

### ISSUE THREAD

**Issue by adem74** [kmcgill88/admob_flutter#296]
Hello, When I try debug on iOS. I get this error.

`[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (< 10.0, = 9.3.0, >= 7.0)

  In Podfile:
    admob_flutter (from `.symlinks/plugins/admob_flutter/ios`) was resolved to 1.0.0, which depends on
      Google-Mobile-Ads-SDK (~> 7.64) was resolved to 7.67.0, which depends on
        GoogleAppMeasurement (~> 6.0)

    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 9.3.1, which depends on
      Firebase/Analytics (= 9.3.0) was resolved to 9.3.0, which depends on
        Firebase/Core (= 9.3.0) was resolved to 9.3.0, which depends on
          FirebaseAnalytics (~> 9.3.0) was resolved to 9.3.0, which depends on
            FirebaseAnalytics/AdIdSupport (= 9.3.0) was resolved to 9.3.0, which depends on
              GoogleAppMeasurement (= 9.3.0)

You have either:
 * changed the constraints of dependency `GoogleAppMeasurement` inside your development pod `admob_flutter`.
   You should run `pod update GoogleAppMeasurement` to apply changes you've made.`

If I change to s.dependency from 7.64 to 9. I got GADInterstitial no in scope error.

**Comment by pavelsust** [comment]
During use this library you can't use google analytics.
