### ISSUE TITLE
No option for adding test device

### ISSUE THREAD

**Issue by newajthevillager** [kmcgill88/admob_flutter#71]
Plugin is good, but so far no option found for adding test device. Adding test device is needed as per admob policy.

**Comment by kmcgill88** [comment]
iOS by default will add the simulator as a test device. Of course, this could (and should) be improved to allow devs to add their own test device ids. @YoussefKababe does the Android side add the emulator as a test device?

@newajthevillager do you have the bandwidth to implement this? PR's welcome!

**Comment by DjaberDribine** [comment]
Android also by default will add the simulator as a test device

**Comment by d-apps** [comment]
This is a very useful option we need, actually this is one of the reasons I'm using firebase_admob plugin instead of this.

**Comment by HusamAamer** [comment]
Since this feature doesn't implemented yet.
I suggest using test unit ids as a workaround to avoid account blocking by admob

**Test ad units here ->** https://developers.google.com/admob/android/test-ads

use it as follows

```
String getInterstitialAdUnitId (){
  if (!kReleaseMode) {
    return 'ca-app-pub-3940256099942544/8691691433'; // TEST UNIT
  }
  
  if (Platform.isIOS) {
    return '.......'; //iOS release unit
  } else {
    return '.......'; //Android release unit
  }
}
```

**Comment by kmcgill88** [comment]
Test devices is now support in `1.0.0-beta.3`. https://github.com/kmcgill88/admob_flutter/pull/169
