### ISSUE TITLE
Build error on IOS

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [kmcgill88/admob_flutter#81]
Launching lib/main.dart on iPhone 8 in debug mode...
Xcode build done.                                            5.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET admob_flutter OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/luja/Desktop/code/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.3/ios/Classes/AdmobFlutterPlugin.m:20:9: fatal error: 'admob_flutter/admob_flutter-Swift.h' file not found
    #import <admob_flutter/admob_flutter-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone 8.
Exited (sigterm)

**Comment by jesusmartinoza** [comment]
It seems that your project wasn't created for Swift.

Try this:
https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios

**Comment by EliasDeuss** [comment]
Did you select iOS when you where creating your project @aleksandar-radivojevic ?

**Comment by aleksandar-radivojevic** [comment]
It's fixed now, it was the Swift problem
