### ISSUE TITLE
why I can‘t use banner ad for ios

### ISSUE THREAD

**Issue by sunjianan9900** [kmcgill88/admob_flutter#86]
0.3.3
it's work on android
but not work on ios:
{error: Request Error: Cannot find an ad network adapter for mediation., errorCode: 8}
no matter using test banner id or my banner id

but interstitial Ad is work on both.

i add this on my plist.info:

```
<key>io.flutter.embedded_views_preview</key>
	<true/>
<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-XXXXX</string>
```

IDE : XCODE 11.2 BETA

**Comment by EliasDeuss** [comment]
@kmcgill88 Can you have a look at this?

**Comment by EliasDeuss** [comment]
Can you do ```flutter doctor -v``` and post the output. @sunjianan9900

**Comment by sunjianan9900** [comment]
> Can you do `flutter doctor -v` and post the output. @sunjianan9900

Have you try ios banners？

**Comment by kmcgill88** [comment]
https://stackoverflow.com/questions/41633253/cannot-find-an-ad-network-adapter


https://support.google.com/admob/thread/3813928?hl=en

**Comment by kmcgill88** [comment]
https://github.com/kmcgill88/admob_flutter/blob/master/example/lib/main.dart#L245

Double check using the correct ideas for the right platform.

**Comment by sunjianan9900** [comment]
> https://github.com/kmcgill88/admob_flutter/blob/master/example/lib/main.dart#L245
> 
> Double check using the correct ideas for the right platform.



Thanks for your reply

I try the demo ios project , it works。
And then I copy and replace the main.dart to my project, it works too.
And then I make main.dart to the second page , put an button on first page to get it , and it doesn't work. And the log print 
`<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
`
And the app stucked.

So I back to the demo project, and make the main.dart code to the second page, and it also Not work.
It seems like jsut work on the first page.
this is the 2file I change from the example:
https://github.com/sunjianan9900/Danmupic/tree/master/demo

**Comment by kmcgill88** [comment]
Have you tried replacing test id's with your own account id's? I'm currently using this code in product and I'm not having any issues. I've also seen this message while I debugged. I'm not sure what else for you to try?

**Comment by sunjianan9900** [comment]
> Have you tried replacing test id's with your own account id's? I'm currently using this code in product and I'm not having any issues. I've also seen this message while I debugged. I'm not sure what else for you to try?

But I can run interstitial ads and reward ads on my demo code using test ad id
-> https://github.com/sunjianan9900/Danmupic/tree/master/demo (just move the ads to second page from example code , not change any id)
interstitial ads and reward ads Can work anywhere , but banner only work on main.dart


It also have the same issues on my release ios app , android not have any issues

**Comment by atereshkov** [comment]
@sunjianan9900 same for me there on IOS. Have you resolved issue with the network adapter error with BANNER type?

**Comment by sunjianan9900** [comment]
> In my case [this one](https://stackoverflow.com/a/35834471/5969121) helped me and now banner ads is showing in the iOS app:
> 
> Open iOS project in Xcode, go to Runner -> Targets -> Runner -> Build Phases -> Link Binary With Libraries
> 
> and here **add iAd.framework**
> 
> ![image](https://user-images.githubusercontent.com/13171457/67634037-47026e00-f8c8-11e9-9f45-5faa9aec6aea.png)
> 
> @kmcgill88 this one also could be documented in some "FAQ" section / etc

it's still not work for me (cry)
<img width="1149" alt="WX20191029-194009@2x" src="https://user-images.githubusercontent.com/10936316/67764778-9c37ae80-fa85-11e9-937d-550db3776870.png">

**Comment by josiasfabricio** [comment]
Same error

<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target. 

> In my case [this one](https://stackoverflow.com/a/35834471/5969121) helped me and now banner ads is showing in the iOS app:
> 
> Open iOS project in Xcode, go to Runner -> Targets -> Runner -> Build Phases -> Link Binary With Libraries
> 
> and here **add iAd.framework**
> 
> ![image](https://user-images.githubusercontent.com/13171457/67634037-47026e00-f8c8-11e9-9f45-5faa9aec6aea.png)
> 
> @kmcgill88 this one also could be documented in some "FAQ" section / etc

Not work for me too

> In my case [this one](https://stackoverflow.com/a/35834471/5969121) helped me and now banner ads is showing in the iOS app:
> 
> Open iOS project in Xcode, go to Runner -> Targets -> Runner -> Build Phases -> Link Binary With Libraries
> 
> and here **add iAd.framework**
> 
> ![image](https://user-images.githubusercontent.com/13171457/67634037-47026e00-f8c8-11e9-9f45-5faa9aec6aea.png)
> 
> @kmcgill88 this one also could be documented in some "FAQ" section / etc

Not work for me too

**Comment by josiasfabricio** [comment]
> In my case [this one](https://stackoverflow.com/a/35834471/5969121) helped me and now banner ads is showing in the iOS app:
> 
> Open iOS project in Xcode, go to Runner -> Targets -> Runner -> Build Phases -> Link Binary With Libraries
> 
> and here **add iAd.framework**
> 
> ![image](https://user-images.githubusercontent.com/13171457/67634037-47026e00-f8c8-11e9-9f45-5faa9aec6aea.png)
> 
> @kmcgill88 this one also could be documented in some "FAQ" section / etc

Not work for me too

**Comment by DigitalSolomon** [comment]
Any improvements with this @josiasfabricio ?

**Comment by josiasfabricio** [comment]
> Any improvements with this @josiasfabricio ?

Unfortunately, no

**Comment by michael-ottink** [comment]
Did you figure out how to do this?

**Comment by sunjianan9900** [comment]
> Did you figure out how to do this? We have the exact same issue

Hey I'm using this : https://github.com/kmcgill88/admob_flutter/issues/86#issuecomment-856589143

**Comment by michael-ottink** [comment]
Yes we are too but we have the same issue, do you have any hints on how to approach the problem? We have AddMob network as our mediation group and no other sources. But we keep getting this error.

**Comment by sunjianan9900** [comment]
sorry I can't remember anything about this, it's too long ago...
