### ISSUE TITLE
Why doesn't the Admob Banner class have a dispose method?

### ISSUE THREAD

**Issue by hkndzdr** [kmcgill88/admob_flutter#94]
Why doesn't the Admob Banner class have a dispose method?

**Comment by kmcgill88** [comment]
Adding this to README FAQ.

Technically the banner class is using `PlatformView` which handles disposing the view for you. 

```dart
onBannerCreated: (AdmobBannerController controller) {
// Dispose is called automatically for you when Flutter removes the banner from the widget tree.
// Normally you don't need to worry about disposing this yourself, it's handled.
// If you need direct access to dispose, this is your guy!
  controller.dispose();
},
```

**Comment by yusriltakeuchi** [comment]
> ```dart
> ();
> ```

@kmcgill88 
I check using devtools, when using controller dispose, the banner still showed in memory.
<img width="639" alt="Screen Shot 2021-11-19 at 14 19 27" src="https://user-images.githubusercontent.com/10339660/142581435-b6ae33ec-be42-4c5f-ab7c-53ecd46142fe.png">

The controller and banner is already to dispose after widget close
<img width="302" alt="Screen Shot 2021-11-19 at 14 19 41" src="https://user-images.githubusercontent.com/10339660/142581532-070a36f4-8f04-4a8b-9741-8a566c039f20.png">
