### ISSUE TITLE
How can i go live?

### ISSUE THREAD

**Issue by Nisthar** [kmcgill88/admob_flutter#98]
Is there any articles which show how to add live ads?

**Comment by atereshkov** [comment]
What do you mean by "live"?

**Comment by Nisthar** [comment]
@atereshkov when i build for production, do i need to change the app id in AndroidManifest.xml or only in the main.dart file?

**Comment by atereshkov** [comment]
@Nisthar you have to change the app ID everywhere in your project. Also don't forget to change banner unit ID as well.
