### ISSUE TITLE
Android phone error: Missing google_app_id. Firebase Analytics disabled

### ISSUE THREAD

**Issue by yytester** [kmcgill88/admob_flutter#99]
when I use test admob id, it can showed on my Android phone. 
But I use my real admob  id  , it can't show on my android phone, and debug info is : `Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOO`.

If I want to use admob_flutter in my product app , I must registered  at firebase  first?

**Comment by Kasiits** [comment]
For me it worked when i published my app.Then i could see live ads with my real amob id.

**Comment by yytester** [comment]
> For me it worked when i published my app.Then i could see live ads with my real amob id.

@Kasiits   hi, do you register at firebase . for your app?     or  you only register at google admob ?

**Comment by Kasiits** [comment]
Only with google admob

**Comment by GioPan-sh** [comment]
@yytester I've your same problem, how do you solve it? Just compiled the release version?
